@startuml
title Firebase Realtime Database - Structură ierarhică

package "Firebase Realtime DataBase" {
  package "Users" {
    class uid {
      + name : String
      + email : String
      + image : String
      + cover : String
      + onlineStatus : String
      + typingTo : String
      + phone : String
      + about : String
      + website : String
    }
  }

  package "Chats" {
    class chatId {
      + sender : String
      + receiver : String
      + message : String
      + type : String
      + timestamp : String
      + isSeen : Boolean
    }
  }

  package "Posts" {
    class postId {
      + uid : String
      + title : String
      + description : String
      + uemail : String
      + uimage : String
      + ptime : String
      + plike : String
      + pcomments : String
    }

    package "Likes" {
      class uid_like {
        + uid : String
        + liked : true
      }
    }

    package "Comments" {
      class commentId {
        + cId : String
        + uid : String
        + comment : String
        + ptime : String
      }
    }
  }
}

@enduml
