@startuml Mini_MVP_Overview

skinparam componentStyle rectangle
skinparam rectangle {
  BackgroundColor #F9F9F9
  BorderColor #555
}


rectangle "View" {
  component "UI (Activity/Fragment)"
}

rectangle "Presenter" {
  component "Presenter Logic"
}

rectangle "Model" {
  component "Business Logic"
  database "Firebase DB"
}


"UI (Activity/Fragment)" --> "Presenter Logic" : UI Event
"Presenter Logic" --> "Business Logic" : Request Data
"Business Logic" --> "Firebase DB" : Access Data
"Firebase DB" --> "Business Logic" : Return Data
"Business Logic" --> "Presenter Logic" : Processed Result
"Presenter Logic" --> "UI (Activity/Fragment)" : Update UI
@enduml
