@startuml
left to right direction
skinparam usecase {
  BackgroundColor #E0F7FA
  BorderColor Black
  ArrowColor Black
}

actor User

package "User Use Cases" {
  usecase "Sign Up" as UC1
  usecase "Sign In" as UC2
  usecase "Reset Password" as UC3
  usecase "Edit Profile" as UC4
  usecase "Add a Post" as UC5
  usecase "Delete a Post" as UC7
  usecase "Share a Post" as UC8
  usecase "View Posts" as UC9
  usecase "Like a Post" as UC10
  usecase "Comment on a Post" as UC11
  usecase "View Likers" as UC12
  usecase "Send Message" as UC13
  usecase "Delete Message" as UC14
  usecase "View Messages" as UC15
  usecase "View Comments" as UC16
  usecase "View Likes" as UC17
  usecase "View Profile" as UC18
  usecase "Search Posts" as UC19
  usecase "Log Out" as UC20

  ' Functionalități noi
  usecase "View Friends List" as UC21
  usecase "View Friend Profile" as UC22
}

User --> UC1
User --> UC2
User --> UC3
User --> UC4
User --> UC5
User --> UC7
User --> UC8
User --> UC9
User --> UC10
User --> UC11
User --> UC12
User --> UC13
User --> UC14
User --> UC15
User --> UC16
User --> UC17
User --> UC18
User --> UC19
User --> UC20
User --> UC21
User --> UC22
@enduml
