@startuml
left to right direction
skinparam usecase {
  BackgroundColor #E0F7FA
  BorderColor Black
  ArrowColor Black
}

actor System

package "System Use Cases" {
  usecase "Retrieve Profile" as SYS1
  usecase "Retrieve Posts" as SYS2
  usecase "Retrieve Comments" as SYS3
  usecase "Retrieve Likes" as SYS4
  usecase "Retrieve Messages" as SYS5
  usecase "Send Notifications" as SYS6
}

System --> SYS1
System --> SYS2
System --> SYS3
System --> SYS4
System --> SYS5
System --> SYS6
@enduml
